before_install:
  - sudo add-apt-repository ppa:n-muench/programs-ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y wireshark=1.12.1

services: mongodb
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head