before_install:
  - sudo add-apt-repository ppa:wireshark/ppa
  - sudp apt-get update -q
  - sudo apt-get insatll tshark=1.12.1+g01b65bf-2~ubuntu14.10.2

services: mongodb
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head