before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libpcap-dev
  - ./ci/install-tshark.sh

services: mongodb
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head